"""
SAM.gov Daily Digest Email Generator

Generates a daily summary email of scan results, recommendations,
and proposal status updates. Designed to be sent via Gmail MCP.
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.storage.db import OpportunityDB


def generate_daily_digest(scan_summary: dict = None) -> dict:
    """
    Generate a daily digest email with scan results and recommendations.

    Returns:
        dict with 'subject', 'content' (HTML), and 'plain_text' fields
    """
    db = OpportunityDB()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    stats = db.get_stats()

    # Build recommendations section
    recs = scan_summary.get("recommendations", []) if scan_summary else []
    rec_count = len(recs)

    # Build email content
    subject = f"SAMgov Daily Digest — {today} | {rec_count} New Recommendations"

    lines = []
    lines.append(f"# SAM.gov Daily Digest — {today}\n")
    lines.append(f"**Scan completed at:** {datetime.now(timezone.utc).strftime('%H:%M UTC')}\n")

    # Summary stats
    lines.append("## Pipeline Summary\n")
    lines.append(f"- **Total opportunities tracked:** {stats.get('total_opportunities', 0)}")
    lines.append(f"- **Active opportunities:** {stats.get('active_count', 0)}")
    lines.append(f"- **New recommendations today:** {rec_count}")
    lines.append(f"- **Proposals in progress:** {stats.get('proposals_in_progress', 0)}")
    lines.append("")

    # Today's recommendations
    if recs:
        lines.append("## Today's Recommendations\n")
        for i, rec in enumerate(recs, 1):
            score = rec.get("fit_score", 0)
            badge = "HIGH FIT" if score >= 85 else "GOOD FIT" if score >= 70 else "CONSIDER"
            lines.append(f"### {i}. [{badge}] {rec.get('title', 'N/A')[:80]}\n")
            lines.append(f"- **Notice ID:** {rec.get('notice_id', 'N/A')}")
            lines.append(f"- **Agency:** {rec.get('agency', 'N/A')}")
            lines.append(f"- **Fit Score:** {score}/100")
            lines.append(f"- **Response Deadline:** {rec.get('response_date', 'N/A')}")
            if rec.get("sam_url"):
                lines.append(f"- **SAM.gov Link:** {rec['sam_url']}")
            lines.append("")
    else:
        lines.append("## No New Recommendations Today\n")
        lines.append("No opportunities met the scoring threshold today. ")
        lines.append("The scanner will continue monitoring daily.\n")

    # Upcoming deadlines
    upcoming = db.get_upcoming_deadlines(days=7) if hasattr(db, 'get_upcoming_deadlines') else []
    if upcoming:
        lines.append("## Upcoming Deadlines (Next 7 Days)\n")
        for opp in upcoming:
            lines.append(f"- **{opp.get('response_date', '')}** — {opp.get('notice_id', '')}: "
                         f"{opp.get('title', '')[:60]} (Score: {opp.get('fit_score', 0)})")
        lines.append("")

    # Action items
    lines.append("## Action Items\n")
    if recs:
        lines.append("1. Review today's recommendations above")
        lines.append("2. For high-fit opportunities, run proposal generator:")
        lines.append("   ```")
        lines.append(f"   python3 main.py --propose <NOTICE_ID>")
        lines.append("   ```")
        lines.append("3. Contact contracting officers for top matches")
    else:
        lines.append("- No immediate actions required")
        lines.append("- Consider expanding search keywords if consistently low results")
    lines.append("")

    lines.append("---\n")
    lines.append("*Generated by SAMgov Agent | Part of Zhang Agent Matrix*")

    content = "\n".join(lines)

    return {
        "subject": subject,
        "content": content,
        "plain_text": content,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "recommendation_count": rec_count,
    }


def generate_mcp_send_command(digest: dict, to_email: str = "junweizhang23@gmail.com") -> str:
    """Generate the MCP CLI command to send the digest email."""
    messages = [{
        "to": [to_email],
        "subject": digest["subject"],
        "content": digest["content"],
    }]
    input_json = json.dumps({"messages": messages})
    return f"manus-mcp-cli tool call gmail_send_messages --server gmail --input '{input_json}'"


if __name__ == "__main__":
    digest = generate_daily_digest()
    print(digest["content"])
    print("\n--- MCP Command ---")
    print(generate_mcp_send_command(digest))
